### ISSUE TITLE
closing the page doesn't redirect to previous one.

### ISSUE THREAD

**Issue by kiryteo** [felicity-iiith/felicity18-website#21]
In the events page, after selecting 'Litcafe', inside that in any of the options e.g. Movie Screening - we get detailed info about the event. After clicking on the close button for the opened pop-up ('x' button), the page just shows just the background although in address bar we can see 'https://felicity.iiit.ac.in/en/'
Same thing happens for all the pages inside 'events'.

Expected - After closing the pop-up it should redirect to last page.

**Comment by meghprkh** [comment]
Fixed on main website
